import Head from "next/head";
import { Main } from "./main/layout";
import Footer from "./footer/layout";

export default async function HomePage() {

  return (
    <>
      <Head>
        <title>Next App with Chakra UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </>
  );
}






